// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Address struct {
	ID         interface{}
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Street     string
	City       string
	PostalCode string
	Country    string
	Latitude   sql.NullFloat64
	Longitude  sql.NullFloat64
}

type Clinic struct {
	ID          interface{}
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Description sql.NullString
	LogoUrl     string
	AddressID   interface{}
	ContactID   interface{}
}

type ClinicDentist struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	ClinicID  interface{}
	DentistID interface{}
}

type Contact struct {
	ID          interface{}
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Email       sql.NullString
	PhoneNumber sql.NullString
}

type Dentist struct {
	ID                interface{}
	CreatedAt         time.Time
	UpdatedAt         time.Time
	FirstName         string
	LastName          string
	Specialization    sql.NullString
	YearsOfExperiance sql.NullInt64
	ImageUrl          string
	UserID            interface{}
	ContactID         interface{}
}
