services:

  booking-db-0:
    image: mongodb/mongodb-community-server:5.0-ubi8
    restart: unless-stopped
    hostname: booking-db-0
    #ports:
    #  - 27017:27017
    volumes:
      - ../booking-db:/app
    command: mongod --replSet rs0 --quiet --logpath /dev/null
    post_start:
      - command: /app/wait-for-it.sh localhost:27017
        user: root
        privileged: true
      - command: /app/initiate-mongo-replSet.sh
        user: root
        privileged: true
    networks:
      mongo-bridge:
        priority: 10
      default:
        aliases:
          - booking-db
    depends_on:
      - booking-db-1
      - booking-db-2

  booking-db-1:
    image: mongodb/mongodb-community-server:5.0-ubi8
    restart: unless-stopped
    hostname: booking-db-1
    #ports:
    #  - 27018:27017
    command: mongod --replSet rs0 --quiet --logpath /dev/null 
    networks:
      mongo-bridge:
        priority: 10
      default:
        aliases:
          - booking-db

  booking-db-2:
    image: mongodb/mongodb-community-server:5.0-ubi8
    restart: unless-stopped
    hostname: booking-db-2
    #ports:
    #  - 27019:27017
    command: mongod --replSet rs0 --quiet --logpath /dev/null 
    networks:
      mongo-bridge:
        priority: 10
      default:
        aliases:
          - booking-db
