services:

  dentist-service:
    build:
      context: ../../dentist-service
      dockerfile: Dockerfile
    restart: unless-stopped
    hostname: dentist-service
    volumes:
      - dentist-db:/data
      - ../../dentist-service:/app
    environment:
      - BROKER_URI=mqtt://message-broker:1883
      - DB_PATH=/data/main.db
    depends_on:
      emqx-node-1:
        condition: service_healthy
      emqx-node-2:
        condition: service_healthy
      emqx-node-3:
        condition: service_healthy
