services:

  booking-db:
    image: mongodb/mongodb-community-server:5.0-ubi8
    restart: unless-stopped 
    hostname: booking-db
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db